### ISSUE TITLE
MILO file

### ISSUE THREAD

**Issue by Smokiiee** [TayMcKenzieNZ/Ranch-De-Caniche#4]
I'm trying to add audio occlusion on this resource but I need MILO file. which of them is it?

**Comment by Smokiiee** [comment]
OR is there no Milo file. i can not find it .if so can you add it maybe ?

**Comment by TayMcKenzieNZ** [comment]
I have no idea.

**Comment by Smokiiee** [comment]
> I have no idea.

Is it something you are able to add it or is it not even in the original?

**Comment by TayMcKenzieNZ** [comment]
Everything provided is what I have, I haven't deliberately left anything out. I'm not knowledgeable in MLOs and whatever it is you're trying to do. I don't even think the original interior had it.

**Comment by Smokiiee** [comment]
> Everything provided is what I have, I haven't deliberately left anything out. I'm not knowledgeable in MLOs and whatever it is you're trying to do. I don't even think the original interior had it.

Oke..

**Comment by Smokiiee** [comment]
> Everything provided is what I have, I haven't deliberately left anything out. I'm not knowledgeable in MLOs and whatever it is you're trying to do. I don't even think the original interior had it.

Would be awesome if you can make and add a 
milo.Ymap file for others if they wanna use audio occlusion

**Comment by TayMcKenzieNZ** [comment]
As I stated, I'm not knowledgeable in MLOs and whatever it is you're trying to do. I don't even think the original interior had it. you are free to do it yourself but as I literally have no idea how I'm not going to bother.

**Comment by TayMcKenzieNZ** [comment]
Try these:

1. https://forum.cfx.re/t/release-la-fuente-blanca-madrazzo-ranch-by-lete/1046939


2. https://forum.cfx.re/t/release-mlo-the-ranch-mafia-cartel/3530943

3. https://forum.cfx.re/t/free-mlo-la-fuente-blanca/4434992

4. GTA5Mods

**Comment by Smokiiee** [comment]
Im going to take a look 😊

**Comment by Smokiiee** [comment]
Don't think this will work. need the right MILO file that all "<Item type="CMloInstanceDef">" is in order.

i going to give you this link there you can read about MILO 
https://forums.gta5-mods.com/topic/19039/milo-starter-guide/2

**Comment by TayMcKenzieNZ** [comment]
Ah ok, well, unfortunately I guess you're out of luck then. Unless you just, create your own MLO and go from there.

I don't have any need for the file myself so I don't really see any point in doing it, plus I don't know how or care enough to learn, sorry.
