### ISSUE TITLE
how i can attach scenario to the object or coords

### ISSUE THREAD

**Issue by hoangpn** [TayMcKenzieNZ/Ranch-De-Caniche#6]
Dear [TayMcKenzieNZ](https://github.com/TayMcKenzieNZ),
This is not an issue, but can you show me how to attach scenario to one object or place like the chairs in your maps.
Many thank and best regards.

**Comment by TayMcKenzieNZ** [comment]
No idea, unfortunately. I use https://github.com/TayMcKenzieNZ/fivem-interactions, but I would assume you can use codewalker or a script to do so.

**Comment by hoangpn** [comment]
Thank for your response, i mean i have some custome map or place, then i want to set a scenario like your doing with Cinema room chairs.

**Comment by TayMcKenzieNZ** [comment]
That chair has it's own scenario attatched to it, it is a rockstar games gta 5 chair, not addon. i do not know how to add scenarios to props, but you can probably do some scripting. Sorry, but I do not know and I have answered your question therefore I can not help.

Good luck.

**Comment by hoangpn** [comment]
I can make a script for coords. But just want to ask if you have good idea for it. 
Thank again, and can i have you discord? then i want send a gift, my cinema (media) system to you.

**Comment by TayMcKenzieNZ** [comment]
I have already answered your questions. I do not know. I am not discussing these matters any further or on discord. good luck.

**Comment by TayMcKenzieNZ** [comment]
Ask the codewalker people how to do it, because I have no freaking idea 

https://discord.gg/MKzzKKxFv8

**Comment by hoangpn** [comment]
> I have already answered your questions. I do not know. I am not discussing these matters any further or on discord. good luck.

Just want to make friend and give you a gift (https://www.youtube.com/watch?v=Jx10oFgsqq0)

**Comment by TayMcKenzieNZ** [comment]
That is a cool script and nice offer, but I use PMMS. Thank you anyways 😄 

https://streamable.com/vwu4zc
